name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1    
    - name: Build and test
      run: sbt jacoco
